"use client";
import React, { useState, useEffect } from 'react';
import { useParams } from 'next/navigation';
import { 
  DollarSign, Leaf, Zap, Globe, Sliders, 
  TrendingDown, CheckCircle2, Award, Download, 
  Layers, Server, Cpu, RefreshCw, AlertCircle, ArrowUpRight
} from 'lucide-react';
import { Card, CardBody, CardHeader } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { DatasetSelector } from '@/components/ui/DatasetSelector';
import { Plot } from '@/components/ui/Plot';
import { api } from '@/lib/api';

interface CloudProviderEstimate {
  provider: string;
  service_name: string;
  instance_type: string;
  vcpus: number;
  ram_gb: number;
  monthly_cost_usd: number;
  cost_per_million_requests: number;
  annual_carbon_kg_co2: number;
  carbon_intensity_rating: string;
  is_cost_winner: boolean;
  is_green_winner: boolean;
}

interface GreenOptimizationItem {
  id: string;
  title: string;
  action: string;
  monthly_savings_usd: number;
  carbon_reduction_pct: number;
  difficulty: string;
  impact_description: string;
}

interface CostCarbonData {
  project_id: string;
  dataset_name?: string;
  daily_requests: number;
  target_p95_latency_ms: number;
  selected_region: string;
  hardware_tier: string;
  spot_enabled: boolean;
  summary: string;
  best_cost_provider: string;
  best_green_provider: string;
  total_potential_monthly_savings: number;
  total_potential_carbon_reduction_kg: number;
  providers: CloudProviderEstimate[];
  optimizations: GreenOptimizationItem[];
  regional_carbon_factors: Record<string, number>;
}

export default function CostCarbonPage() {
  const params = useParams();
  const projectId = params.id as string;

  const [datasets, setDatasets] = useState<any[]>([]);
  const [selectedDataset, setSelectedDataset] = useState<string | null>(null);

  // Configuration States
  const [dailyRequests, setDailyRequests] = useState<number>(100000);
  const [targetLatency, setTargetLatency] = useState<number>(25);
  const [region, setRegion] = useState<string>("us-east-1 (N. Virginia - Gas/Coal)");
  const [hardwareTier, setHardwareTier] = useState<string>("cpu_standard");
  const [spotEnabled, setSpotEnabled] = useState<boolean>(false);

  const [data, setData] = useState<CostCarbonData | null>(null);
  const [loading, setLoading] = useState(true);
  const [calculating, setCalculating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    loadDatasetsAndEstimate();
  }, [projectId]);

  const loadDatasetsAndEstimate = async () => {
    try {
      setLoading(true);
      setError(null);
      const dsData = await api.datasets.list(projectId);
      const list = Array.isArray(dsData) ? dsData : [];
      setDatasets(list);

      const defaultDsId = list.length > 0 ? list[0].id : undefined;
      if (defaultDsId) {
        setSelectedDataset(defaultDsId);
      }

      const res = await api.costCarbon.getEstimate(projectId, defaultDsId);
      setData(res);
    } catch (err: any) {
      setError(err.message || 'Failed to load cost and carbon estimate');
    } finally {
      setLoading(false);
    }
  };

  const reCalculate = async (
    reqs = dailyRequests,
    lat = targetLatency,
    reg = region,
    hw = hardwareTier,
    spot = spotEnabled
  ) => {
    try {
      setCalculating(true);
      const res = await api.costCarbon.calculate(projectId, {
        dataset_id: selectedDataset || undefined,
        daily_requests: reqs,
        target_p95_latency_ms: lat,
        region: reg,
        hardware_tier: hw,
        spot_enabled: spot
      });
      setData(res);
    } catch (err: any) {
      setError(err.message || 'Calculation update failed');
    } finally {
      setCalculating(false);
    }
  };

  const handleDatasetSelect = async (datasetId: string) => {
    setSelectedDataset(datasetId);
    await reCalculate(dailyRequests, targetLatency, region, hardwareTier, spotEnabled);
  };

  const downloadTerraformBlueprint = () => {
    if (!data) return;
    const tfContent = `# Terraform MLOps Multi-Cloud Infrastructure Blueprint
# Auto-generated by AutoMLOps Cost & Carbon Optimizer
# Daily Volume: ${data.daily_requests.toLocaleString()} req/day | SLA: ${data.target_p95_latency_ms}ms
# Region: ${data.selected_region}

variable "project_id" {
  default = "${projectId}"
}

# Best Cost Provider Architecture: ${data.best_cost_provider}
# Best Green Provider Architecture: ${data.best_green_provider}

# Spot Instances Enabled: ${data.spot_enabled}
# Hardware Tier: ${data.hardware_tier}

output "estimated_monthly_cost" {
  value = "$${data.providers[0]?.monthly_cost_usd}/mo"
}

output "annual_carbon_kg_co2" {
  value = "${data.providers[0]?.annual_carbon_kg_co2} kg CO2e"
}
`;
    const blob = new Blob([tfContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `mlops_infrastructure_blueprint.tf`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const getEcoBadgeClass = (rating: string) => {
    switch (rating) {
      case 'A+':
      case 'A':
        return 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40';
      case 'B':
        return 'bg-cyan-500/20 text-cyan-300 border-cyan-500/40';
      case 'C':
        return 'bg-amber-500/20 text-amber-300 border-amber-500/40';
      default:
        return 'bg-red-500/20 text-red-300 border-red-500/40';
    }
  };

  // Plotly chart data for Cost & Carbon
  const getPlotData = () => {
    if (!data?.providers) return [];

    const names = data.providers.map(p => p.provider);
    const costs = data.providers.map(p => p.monthly_cost_usd);
    const carbons = data.providers.map(p => p.annual_carbon_kg_co2);

    return [
      {
        x: names,
        y: costs,
        name: 'Monthly Cost ($/mo)',
        type: 'bar' as const,
        marker: { color: '#06B6D4' }
      },
      {
        x: names,
        y: carbons,
        name: 'Annual Carbon (kg CO₂e/yr)',
        type: 'bar' as const,
        marker: { color: '#10B981' }
      }
    ];
  };

  const plotLayout = {
    paper_bgcolor: 'transparent',
    plot_bgcolor: 'transparent',
    font: { color: '#F9FAFB', size: 11 },
    barmode: 'group' as const,
    xaxis: { gridcolor: '#1f293d' },
    yaxis: { title: 'Cost ($) / Carbon (kg)', gridcolor: '#1f293d' },
    margin: { t: 20, b: 40, l: 50, r: 20 },
    legend: { orientation: 'h' as const, y: -0.2 }
  };

  return (
    <div className="space-y-8 animate-fade-in">
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <div className="p-1.5 rounded-lg bg-gradient-to-r from-emerald-500/20 to-cyan-500/20 border border-emerald-500/40">
              <Leaf className="w-5 h-5 text-emerald-400" />
            </div>
            <span className="text-xs font-bold uppercase tracking-wider text-emerald-400">Green MLOps & Sustainability</span>
          </div>
          <h1 className="text-3xl font-bold font-heading">Cost & Carbon Optimizer</h1>
          <p className="text-gray-400 text-sm">
            Model infrastructure spend, power usage, and carbon emissions across AWS, GCP, Azure, and On-Premise.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <Button 
            variant="secondary" 
            onClick={downloadTerraformBlueprint}
            disabled={!data || loading}
            className="flex items-center gap-1.5 text-xs"
          >
            <Download className="w-3.5 h-3.5" />
            Export Terraform
          </Button>
        </div>
      </div>

      {/* Dataset Selector */}
      <DatasetSelector
        datasets={datasets}
        selectedDatasetId={selectedDataset}
        onSelect={handleDatasetSelect}
        projectId={projectId}
        label="Dataset For Infrastructure Sizing"
      />

      {error && (
        <div className="glass border-red-500/30 bg-red-500/10 p-4 rounded-xl text-red-400 text-sm flex items-center gap-2">
          <AlertCircle className="w-4 h-4 shrink-0" />
          <span>{error}</span>
        </div>
      )}

      {/* Main Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column: Traffic & Hardware Configurator (5 cols) */}
        <div className="lg:col-span-5 space-y-4">
          <Card glow>
            <CardHeader className="pb-3 border-b border-white/10">
              <div className="flex items-center gap-2">
                <Sliders className="w-4 h-4 text-cyan-400" />
                <h3 className="font-bold text-sm sm:text-base text-white">Workload & Cloud Sizing</h3>
              </div>
            </CardHeader>

            <CardBody className="p-4 space-y-5">
              {/* Daily Request Volume Slider */}
              <div className="space-y-2">
                <div className="flex justify-between items-center text-xs">
                  <span className="font-bold text-white">Daily Inference Volume</span>
                  <span className="font-mono font-bold text-cyan-300 bg-cyan-500/10 px-2 py-0.5 rounded border border-cyan-500/30">
                    {dailyRequests.toLocaleString()} req/day
                  </span>
                </div>
                <input
                  type="range"
                  min={10000}
                  max={2000000}
                  step={10000}
                  value={dailyRequests}
                  onChange={(e) => {
                    const val = parseInt(e.target.value);
                    setDailyRequests(val);
                    reCalculate(val, targetLatency, region, hardwareTier, spotEnabled);
                  }}
                  className="w-full h-1.5 bg-white/20 rounded-lg appearance-none cursor-pointer accent-cyan-400"
                />
                <div className="flex justify-between text-[10px] text-gray-500 font-mono">
                  <span>10K / day</span>
                  <span>1M / day</span>
                  <span>2M+ / day</span>
                </div>
              </div>

              {/* Target SLA Latency Slider */}
              <div className="space-y-2">
                <div className="flex justify-between items-center text-xs">
                  <span className="font-bold text-white">P95 SLA Target Latency</span>
                  <span className="font-mono font-bold text-emerald-300 bg-emerald-500/10 px-2 py-0.5 rounded border border-emerald-500/30">
                    {targetLatency}ms
                  </span>
                </div>
                <input
                  type="range"
                  min={10}
                  max={100}
                  step={5}
                  value={targetLatency}
                  onChange={(e) => {
                    const val = parseInt(e.target.value);
                    setTargetLatency(val);
                    reCalculate(dailyRequests, val, region, hardwareTier, spotEnabled);
                  }}
                  className="w-full h-1.5 bg-white/20 rounded-lg appearance-none cursor-pointer accent-emerald-400"
                />
                <div className="flex justify-between text-[10px] text-gray-500 font-mono">
                  <span>10ms (Realtime)</span>
                  <span>50ms (Interactive)</span>
                  <span>100ms (Standard)</span>
                </div>
              </div>

              {/* Datacenter Region Picker */}
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-white flex items-center gap-1.5">
                  <Globe className="w-3.5 h-3.5 text-cyan-400" />
                  <span>Datacenter Grid Region</span>
                </label>
                <select
                  value={region}
                  onChange={(e) => {
                    setRegion(e.target.value);
                    reCalculate(dailyRequests, targetLatency, e.target.value, hardwareTier, spotEnabled);
                  }}
                  className="w-full bg-[#10182b] border border-white/15 rounded-lg px-2.5 py-2 text-xs text-white focus:outline-none focus:border-cyan-500 cursor-pointer"
                >
                  {Object.keys(data?.regional_carbon_factors || {}).map(r => (
                    <option key={r} value={r} className="bg-[#0e1628] text-white">{r}</option>
                  ))}
                </select>
              </div>

              {/* Hardware Accelerator Tier */}
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-white flex items-center gap-1.5">
                  <Cpu className="w-3.5 h-3.5 text-purple-400" />
                  <span>Compute Architecture</span>
                </label>
                <div className="grid grid-cols-3 gap-2">
                  {[
                    { id: 'cpu_standard', label: 'Standard CPU', sub: 'x86_64' },
                    { id: 'arm_graviton', label: 'ARM Graviton', sub: '-20% Cost' },
                    { id: 'gpu_t4', label: 'NVIDIA T4', sub: 'GPU Accel' }
                  ].map(hw => (
                    <button
                      key={hw.id}
                      onClick={() => {
                        setHardwareTier(hw.id);
                        reCalculate(dailyRequests, targetLatency, region, hw.id, spotEnabled);
                      }}
                      className={`p-2.5 rounded-xl border text-center transition-all ${
                        hardwareTier === hw.id
                          ? 'bg-cyan-500/20 border-cyan-500 text-white font-bold'
                          : 'bg-white/5 border-white/10 text-gray-400 hover:text-white'
                      }`}
                    >
                      <div className="text-xs">{hw.label}</div>
                      <div className="text-[10px] text-gray-400">{hw.sub}</div>
                    </button>
                  ))}
                </div>
              </div>

              {/* Spot / Preemptible Toggle */}
              <div className="pt-3 border-t border-white/10 flex items-center justify-between">
                <div>
                  <span className="text-xs font-bold text-white block">Spot / Preemptible Instances</span>
                  <span className="text-[11px] text-gray-400">Up to 70% cloud compute discount</span>
                </div>
                <button
                  onClick={() => {
                    const updated = !spotEnabled;
                    setSpotEnabled(updated);
                    reCalculate(dailyRequests, targetLatency, region, hardwareTier, updated);
                  }}
                  className={`w-11 h-6 rounded-full transition-colors relative p-0.5 ${
                    spotEnabled ? 'bg-emerald-500' : 'bg-white/20'
                  }`}
                >
                  <div className={`w-5 h-5 rounded-full bg-white transition-transform ${
                    spotEnabled ? 'translate-x-5' : 'translate-x-0'
                  }`} />
                </button>
              </div>
            </CardBody>
          </Card>
        </div>

        {/* Right Column: Multi-Cloud Comparison & Green MLOps (7 cols) */}
        <div className="lg:col-span-7 space-y-6">
          {/* Executive Synthesis Banner */}
          {data && (
            <div className="glass rounded-2xl p-5 border border-white/10 bg-gradient-to-br from-[#0d1e28] via-[#0d1424] to-[#0a0f1d] space-y-4">
              <div className="flex flex-wrap items-center justify-between gap-2">
                <div className="flex items-center gap-2">
                  <Award className="w-4 h-4 text-emerald-400" />
                  <span className="text-xs font-bold uppercase tracking-wider text-emerald-400">Multi-Cloud Evaluation</span>
                </div>

                <div className="flex items-center gap-2">
                  <span className="px-2.5 py-0.5 rounded-lg text-xs font-bold bg-cyan-500/20 text-cyan-300 border border-cyan-500/40">
                    💰 Cost Winner: {data.best_cost_provider}
                  </span>
                  <span className="px-2.5 py-0.5 rounded-lg text-xs font-bold bg-emerald-500/20 text-emerald-300 border border-emerald-500/40">
                    🌱 Eco Winner: {data.best_green_provider}
                  </span>
                </div>
              </div>

              <p className="text-xs sm:text-sm text-gray-200 leading-relaxed font-normal">
                {data.summary}
              </p>
            </div>
          )}

          {/* 4 Multi-Cloud Provider Cards Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {data?.providers?.map((prov) => (
              <div 
                key={prov.provider}
                className={`glass rounded-2xl p-4 border transition-all ${
                  prov.is_cost_winner
                    ? 'border-cyan-500/40 bg-cyan-500/5'
                    : prov.is_green_winner
                    ? 'border-emerald-500/40 bg-emerald-500/5'
                    : 'border-white/10 bg-[#0d1424]/80'
                }`}
              >
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center gap-1.5">
                    <Server className="w-4 h-4 text-cyan-400" />
                    <span className="text-xs font-bold text-white">{prov.provider}</span>
                  </div>
                  <span className={`px-2 py-0.5 rounded text-[10px] font-bold border ${getEcoBadgeClass(prov.carbon_intensity_rating)}`}>
                    Eco: {prov.carbon_intensity_rating}
                  </span>
                </div>

                <span className="text-[11px] text-gray-400 block mb-3 font-mono">{prov.service_name}</span>

                <div className="space-y-1.5 text-xs">
                  <div className="flex justify-between items-baseline">
                    <span className="text-gray-400">Monthly Cost:</span>
                    <span className="text-base font-bold text-white font-mono">${prov.monthly_cost_usd}</span>
                  </div>
                  <div className="flex justify-between text-gray-400 text-[11px]">
                    <span>Cost / 1M Reqs:</span>
                    <span className="text-cyan-300 font-mono">${prov.cost_per_million_requests}</span>
                  </div>
                  <div className="flex justify-between text-gray-400 text-[11px] pt-1 border-t border-white/5">
                    <span>Annual CO₂ Footprint:</span>
                    <span className="text-emerald-400 font-mono font-semibold">{prov.annual_carbon_kg_co2} kg</span>
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* Interactive Cost & Carbon Bar Plot */}
          <Card glow>
            <CardHeader className="pb-2 border-b border-white/10">
              <div className="flex items-center gap-2">
                <TrendingDown className="w-4 h-4 text-cyan-400" />
                <h3 className="font-bold text-sm sm:text-base text-white">Monthly Spend vs Carbon Comparison</h3>
              </div>
            </CardHeader>
            <CardBody className="h-[260px]">
              <Plot
                data={getPlotData()}
                layout={plotLayout}
                useResizeHandler
                style={{ width: '100%', height: '100%' }}
                config={{ displayModeBar: false }}
              />
            </CardBody>
          </Card>

          {/* Green MLOps Optimizations */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold text-gray-400 uppercase tracking-wider flex items-center gap-1.5">
              <Zap className="w-3.5 h-3.5 text-emerald-400" /> Actionable Sustainability Recommendations
            </h4>

            <div className="grid grid-cols-1 gap-3">
              {data?.optimizations?.map((opt) => (
                <div key={opt.id} className="glass rounded-xl p-3.5 border border-white/10 bg-white/5 space-y-1.5">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-white">{opt.title}</span>
                    <div className="flex items-center gap-1.5">
                      {opt.monthly_savings_usd > 0 && (
                        <span className="text-[10px] font-mono font-bold text-cyan-300 bg-cyan-500/10 px-2 py-0.5 rounded border border-cyan-500/30">
                          Save ${opt.monthly_savings_usd}/mo
                        </span>
                      )}
                      {opt.carbon_reduction_pct > 0 && (
                        <span className="text-[10px] font-mono font-bold text-emerald-300 bg-emerald-500/10 px-2 py-0.5 rounded border border-emerald-500/30">
                          -{opt.carbon_reduction_pct}% CO₂
                        </span>
                      )}
                    </div>
                  </div>
                  <p className="text-[11px] text-gray-300 leading-relaxed">{opt.action}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
